############################GENERAL#####################################################################################
organism:
  hs: "Homo_sapiens"
  mm: "Mus_musculus"
  rn: "Rattus_norvegicus"

# Push through pipeline only priority datasets
priority_only_f: "False"

# KALLISTO N_BOOTSTRAP
n_bootstrap: 0

#############################RESOURSES##################################################################################
quant_mem_ram:
  hs: 12
  mm: 10
  rn: 5

#############################LINKS######################################################################################
sra_accession_df: "ftp://ftp.ncbi.nlm.nih.gov/sra/reports/Metadata/SRA_Accessions.tab"

#############################FILTERS####################################################################################
## Pre-quantification filters
quant_min_gsm: 2
quant_max_gsm: 400

## Single cell QC
# to distinguish between single cell and bulk samples are filtered by the number of spots per GSM

min_spots:
  hs: 1000000
  mm: 1000000
  rn: 1000000

max_spots:
  hs: 108716485
  mm: 102951239
  rn: 89641872

min_exp_genes:
  hs: 14000
  mm: 6000
  rn: 13000

min_gsm: 2
max_gsm: 400

min_gse_pca: 2
max_gse_pca: 200

chip_logmax_max: 20
chip_linmax_max: 100000 # original:2000
chip_logav_min: 4
chip_logav_max: 10
# todo: add other organisms
min_exp_genes: 6000

#############################PCA_PARAMS#################################################################################
# parameters shold be in string format so that they can be passed to folders names
pca_min_gsm: 2
pca_max_gsm: 400
pca_n_genes: "6000"
pca_scale: "log"

#############################WGCNA_PARAMS###############################################################################
# parameters should be written in camel case, because they go to folder name for each particular setting.
# Scripts should be adapted to parse this arguments

# general dataset size boundaries
min_gsm_wgcna: 8
max_gsm_wgcna: 200

# Number of genes considered in clusterization
wgcna_n_genes:
  - "6000"
  - "8000"
  - "10000"
# WGCNA correlation function
wgcna_cor: "pearson"
# WGCNA network type
wgcna_nt: "signedHybrid"
# Scaling matrices (log/linear)
scale: "log"
