############################GENERAL#####################################################################################
organism:
  hs: "Homo_sapiens"
  mm: "Mus_musculus"
  rn: "Rattus_norvegicus"

# Push through pipeline only priority datasets
priority_only_f: "False"

#############################RESOURSES##################################################################################
quant_mem_ram:
  hs: 12
  mm: 10
  rn: 5

#############################LINKS######################################################################################
sra_accession_df: "ftp://ftp.ncbi.nlm.nih.gov/sra/reports/Metadata/SRA_Accessions.tab"

#############################FILTERS####################################################################################
## Pre-quantification filters
quant_min_gsm: 2
quant_max_gsm: 400

## Single cell QC
# to distinguish between single cell and bulk samples are filtered by the number of spots per GSM

min_spots:
  hs: 1000000
  mm: 1000000
  rn: 1000000

max_spots:
  hs: 108716485
  mm: 10000000
  rn: 83583852

min_exp_genes:
  hs: 14000
  mm: 6000
  rn: 13000

min_gse_gq: 8
max_gse_gq: 200
min_gse_pca: 2
max_gse_pca: 200

#############################WGCNA_PARAMS###############################################################################
# Number of genes considered in clusterization
wgcna_n_genes: 6000
# WGCNA correlation function
wgcna_cor: "pearson"
# WGCNA network type
wgcna_nt: "signed hybrid"
