############################GENERAL#####################################################################################
organism: "Homo_sapience"

# Push through pipeline only priority datasets
priority_only_f: "True"
############################INPUT_FILES#################################################################################
geo_search_result_chip: "input/hs/gds_search_seq.txt"
priority_gse_list: "input/hs/priority_gse_list"
refseq: "input/hs/genprime_v29_nopar_kallisto"
probes_to_genes: "input/hs/genprime_v29.gene_tr.tsv"
ensamble_genesymbol_entrez: "input/hs/genprime_v29.gene_name_entrez.tsv"
gpl_df: "input/gpl.tsv"

#############################LINKS######################################################################################
sra_accession_df: "ftp://ftp.ncbi.nlm.nih.gov/sra/reports/Metadata/SRA_Accessions.tab"

#############################FILTERS####################################################################################
## Pre-quantification filters
quant_min_gsm: 2
quant_max_gsm: 400
# to distinguish between single cell and bulk samples are filtered by the number of spots per GSM
min_spots_gsm: 1000000
max_spots_gsm: 108716485

## WGCNA filters
min_exp_genes: 14000
min_gse_gq: 8
max_gse_gq: 200
min_gse_pca: 2
max_gse_pca: 200

#############################WGCNA_PARAMS###############################################################################
# Number of genes considered in clusterization
wgcna_n_genes: 6000
# WGCNA correlation function
wgcna_cor: "pearson"
# WGCNA network type
wgcna_nt: "signed hybrid"
