# TODO: add list of acceptable platforms
# TODO: add 3cols(or rule to get to 3cols)
############################GENERAL#####################################################################################
organism: "Rattus_norvegicus"

# Push through pipeline only priority datasets
# If flag is False priority GSE will be pushed through along with passed QC GSE
priority_only_f: "True"
############################INPUT_FILES#################################################################################
geo_search_result_chip: "input/rn/gds_search_seq.txt"
priority_gse_list: "input/rn/priority_gse_list"
refseq: "input/rn/rnor_v6_kallisto"
probes_to_genes: "input/rn/Rnor_6.0.98.gene_tr.tsv"
ensamble_genesymbol_entrez: "input/rn/rnor_v6.gene_name_entrez.tsv"
gpl_df: "input/gpl.tsv"

#############################LINKS######################################################################################
sra_accession_df: "ftp://ftp.ncbi.nlm.nih.gov/sra/reports/Metadata/SRA_Accessions.tab"

#############################FILTERS####################################################################################
## Pre-quantification filters
quant_min_gsm: 2
quant_max_gsm: 400
# to distinguish between single cell and bulk samples are filtered by the number of spots
min_spots_gsm: 1000000
max_spots_gsm: 83583852

## WGCNA filters
min_exp_genes: 4000 #13000
min_gse_gq: 8 #8
max_gse_gq: 200
min_gse_pca: 2
max_gse_pca: 200

#############################WGCNA_PARAMS###############################################################################
# Number of genes considered in clusterization
wgcna_n_genes: 6000
# WGCNA correlation function
wgcna_cor: "pearson"
# WGCNA network type
wgcna_nt: "signed hybrid"
